armbot: 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wist_position_controller:
    type: effort_controllers/JointPositionController
    joint: wist
    pid: {p: 100.0, i: 0.01, d: 10.0}

