my_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  base_position_controller:
    type: effort_controllers/JointPositionController
    joint: base
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wist_position_controller:
    type: effort_controllers/JointPositionController
    joint: wist
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_finger_position_controller:
    type: effort_controllers/JointPositionController
    joint: hand_to_left_finger
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_finger_position_controller:
    type: effort_controllers/JointPositionController
    joint: hand_to_right_finger
    pid: {p: 100.0, i: 0.01, d: 10.0}